[example]
description = "Hyprland plugin to make borders more useful with a mouse"
version = "0.1.0"
author = "horriblename"

[example.build]
output = "build/libhyprland-useful-borders.so"
steps = [
    "meson setup build",
	 "ninja -C build"
]
