[border-actions]
description = "Hyprland plugin to make borders more useful with a mouse"
version = "0.1.0"
author = "horriblename"

[border-actions.build]
output = "build/libborder-actions.so"
steps = [
    "meson setup build",
	 "ninja -C build"
]
